export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_RECIPES_PRENDING = 'REQUEST_RECIPES_PRENDING';
export const REQUEST_RECIPES_SUCCESS = 'REQUEST_RECIPES_SUCCESS';
export const REQUEST_RECIPES_FAILED = 'REQUEST_RECIPES_FAILED';
